#!/bin/bash
# Quick reference: React Native Best Practices Checklist
# Run: ./scripts/checklist.sh

echo "📱 React Native 2026 Best Practices Checklist"
echo "=============================================="
echo ""
echo "🏗️  ARCHITECTURE"
echo "  □ Feature-based organization (not by file type)"
echo "  □ Single responsibility per component"
echo "  □ Business logic isolated from UI"
echo "  □ Centralized service layer"
echo "  □ TypeScript strict mode enabled"
echo ""
echo "⚡  PERFORMANCE"
echo "  □ FlatList for scrollable data"
echo "  □ React.memo for expensive components"
echo "  □ useMemo for expensive calculations"
echo "  □ useCallback for stable references"
echo "  □ StyleSheet.create (no inline objects)"
echo "  □ No unnecessary re-renders"
echo ""
echo "🔄  STATE MANAGEMENT (Zustand)"
echo "  □ Separate stores by domain"
echo "  □ Select only needed data (not entire store)"
echo "  □ Actions are pure functions"
echo "  □ Async actions handle errors"
echo "  □ Real-time subscriptions cleanup"
echo ""
echo "🎨  UI/UX"
echo "  □ Safe area handling"
echo "  □ Loading states (skeletons/spinners)"
echo "  □ Error states with retry"
echo "  □ Empty states"
echo "  □ Responsive design (Dimensions API)"
echo "  □ Accessibility (a11y labels)"
echo ""
echo "🔐  SECURITY"
echo "  □ Sensitive data in SecureStore (not AsyncStorage)"
echo "  □ Environment variables validated"
echo "  □ No console.log in production"
echo "  □ RLS policies on all tables"
echo "  □ E2E encryption implemented"
echo ""
echo "🧪  TESTING"
echo "  □ Unit tests for utilities (80%+ coverage)"
echo "  □ Component tests for UI"
echo " □ Hook tests with renderHook"
echo "  □ Mock external services"
echo "  □ Error cases tested"
echo ""
echo "🚀  DEPLOYMENT"
echo "  □ EAS build configured"
echo "  □ OTA updates for JS-only changes"
echo "  □ Version bumping automated"
echo "  □ Error tracking (Sentry)"
echo "  □ Performance monitoring"
echo ""
echo "📝  CODE QUALITY"
echo "  □ ESLint passing"
echo "  □ TypeScript strict (no 'any')"
echo "  □ Components have props interfaces"
echo "  □ Error boundaries implemented"
echo "  □ No dead code/unused imports"
echo ""
